/// <reference lib="webworker" />

/**
 * Chat Buddy's service worker.
 *
 * Hand-written rather than generated by Workbox. The caching this app needs is
 * modest — precache a content-hashed shell, serve it offline — and `vite-plugin-pwa`
 * brought in `workbox-build`, whose dependency tree carried every high-severity
 * advisory in the project and pinned Babel 7, which in turn forced an npm override to
 * install `@vitejs/plugin-react`. Fifty lines here removed all of that.
 *
 * Built by `plugins/service-worker.ts`, which transpiles this file and substitutes the
 * two placeholders below with the real build output. It never runs in dev, where Vite
 * serves modules directly and a cache would only get in the way.
 *
 * The bug worth not repeating: v1's `activate` handler computed the set of caches to
 * keep *without* the cache `install` had just populated, so the precached shell was
 * deleted the moment the worker activated and offline never actually worked. Hence
 * `isCurrentCache` below, and a test for it.
 */

const worker = self as unknown as ServiceWorkerGlobalScope;

/*
 * Build-time placeholders, substituted by the plugin before transpiling.
 *
 * The `__NAME__` form is the conventional marker for a value injected by the build —
 * it is what Vite's own `define` uses — so it is worth keeping over a name the linter
 * would prefer. The plugin matches these exact strings.
 */

/**
 * A hash of the precache list. A new hash means a new cache name, which is what makes
 * an old shell collectable.
 */
// biome-ignore lint/style/useNamingConvention: build-time substitution placeholder.
declare const __SW_VERSION__: string;

/** The content-hashed files making up the app shell. */
// biome-ignore lint/style/useNamingConvention: build-time substitution placeholder.
declare const __SW_PRECACHE__: readonly string[];

const CACHE_PREFIX = "chat-buddy-shell-";
const CACHE_NAME = `${CACHE_PREFIX}${__SW_VERSION__}`;

/** The document served for any navigation, since the app is a single page. */
const APP_SHELL = "/index.html";

/** True for caches this worker owns. Anything else is a previous build's. */
function isCurrentCache(name: string): boolean {
  return name === CACHE_NAME;
}

function isManagedCache(name: string): boolean {
  return name.startsWith(CACHE_PREFIX);
}

worker.addEventListener("install", (event) => {
  /*
   * Deliberately no `skipWaiting()`.
   *
   * A new worker waits until the page asks for it, so an update can never swap the
   * app out from under a reply that is mid-generation. `register-sw.ts` prompts, and
   * only then posts the message handled below.
   */
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      // `reload` bypasses the HTTP cache, so a precache never stores a stale copy.
      await cache.addAll(
        __SW_PRECACHE__.map((url) => new Request(url, { cache: "reload" })),
      );
    })(),
  );
});

worker.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names
          .filter((name) => isManagedCache(name) && !isCurrentCache(name))
          .map((name) => caches.delete(name)),
      );

      // Take over pages that were loaded before this worker existed.
      await worker.clients.claim();
    })(),
  );
});

worker.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") void worker.skipWaiting();
});

worker.addEventListener("fetch", (event) => {
  const { request } = event;

  // Never interfere with anything but plain same-origin reads. Cross-origin traffic
  // includes the model weights, which the inference engine caches itself and which
  // would blow past any sensible quota here.
  if (request.method !== "GET") return;
  if (new URL(request.url).origin !== worker.location.origin) return;

  /*
   * Navigations: network first, cached shell as the fallback.
   *
   * The other way round would serve a stale document to an online visitor, and
   * because `index.html` references hashed assets, a stale one can point at files
   * that no longer exist.
   */
  if (request.mode === "navigate") {
    event.respondWith(
      (async () => {
        try {
          return await fetch(request);
        } catch {
          const cache = await caches.open(CACHE_NAME);
          const shell = await cache.match(APP_SHELL);
          return shell ?? Response.error();
        }
      })(),
    );
    return;
  }

  // Precached assets: cache first. Their names contain a content hash, so a cached
  // copy can never be the wrong version.
  event.respondWith(
    (async () => {
      const cached = await caches.match(request, { cacheName: CACHE_NAME });
      if (cached) return cached;

      // Anything else — a lazily-loaded chunk, an image — is fetched normally and
      // left to the HTTP cache. Storing it here would grow the cache unboundedly.
      return fetch(request);
    })(),
  );
});
